### ISSUE TITLE
Adding Bagmati Province data

### ISSUE THREAD

**Issue by yube01** [prab33n/Explore-Unexplored-Nepal#20]
Data related to Bagmati province could be added

**Comment by yube01** [comment]
@ori-on1 can you please add the hactoberfest label

**Comment by prab33n** [comment]
Please add some of your contributions to get a Hacktoberfest accepted label.

**Comment by ori-on1** [comment]
label is already added to the repo. You will get a label only after making
a contribution.

**Comment by ori-on1** [comment]
Issue closed successfully.
